### ISSUE TITLE
[RFC] Make id name customisable in crud controllers

### ISSUE THREAD

**Issue by Nek-** [biig-io/Melodiia#64]
### Current behavior
 
```yaml
lead_update:
    path: /api/v1/leads/{idLead}
    controller: 'melodiia.crud.controller.update'
    methods: ['PATCH']
    defaults: # ...
```
This configuration fails with error message:
```
Could not resolve argument $id of \"melodiia.crud.controller.update()\", maybe you forgot to register the controller as a service or missed tagging it with the \"controller.service_arguments\"?
```

### Expected behavior

Support the ability to change the name of the id.

### Implementation suggestion

Add a new method in the base controller that is able to guess what is the id field (based on the assumption that the id will always start by id).

Also, add a new configuration option that allows specifying a custom id.

### Current workaround

~~Since controllers are final, there's no workaround. They should not be final.~~

Not that great. But override the entire controller. It's fine. Making your own controller is not a bad practice in Melodiia context.
